application:
  name: spacemission-manager
  description: A small Spring microservice aimed towards both governance, management and operational tasks applied towards for the various space mission resources within the Spaceover platform.
  version: 1.0.0

feign:
  circuitbreaker:
    enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 5
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException

server:
  port: 8082

spring:
  application:
    name: spacemission-manager
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 100

spaceship-manager:
  client:
    provider: open-feign

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/"

open-api:
  header:
    pagination:
      enabled: false
