application:
  name: spacecrew-manager
  description: A small Spring microservice aimed towards both governance, management and operational tasks applied towards for the various crew member resources within the Spaceover platform.
  version: 1.0.0

server:
  port: 8081

spring:
  application:
    name: spacecrew-manager
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 100

spaceship-manager:
  client:
    provider: rest-template

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/"

open-api:
  header:
    pagination:
      enabled: false
